services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-fpm-container
    volumes:
      - .:/var/www/html
      - vendor_volume:/var/www/html/vendor
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
      echo 'Ожидание запуска сервиса MySQL...';
      sleep 5 &&
      chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
      php artisan migrate &&
      php artisan optimize:clear &&
      php artisan config:cache &&
      php artisan route:cache &&
      docker-php-entrypoint php-fpm"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  mysql:
    image: mysql:8.4
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  db_data:
  vendor_volume: